#
# To deploy:
#
# kubectl apply -f deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arithmetic-service
  template:
    metadata:
      labels:
        app: arithmetic-service
    spec:
      containers: 
      - name: arithmetic-service
        image: pract16.azurecr.io/arithmetic-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: arithmetic-service
spec:
  selector:
    app: arithmetic-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
