name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username abankhel --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/abankhel/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/abankhel/arithmetic-service:latest 
            - name: Build and push the imag
              run: |
                docker login --username pract16 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} pract16.azurecr.io
                docker tag ghcr.io/abankhel/arithmetic-service:latest pract16.azurecr.io/arithmetic-service:latest 
                docker push pract16.azurecr.io/abankhel/arithmetic-service:latest
